rnin9/KT-ds-University-17th-web-application-project

src/main/java/com/mySpring/springEx/member/service/MemberService.java
src/main/java/com/mySpring/springEx/member/service/MemberServiceImpl.java
src/main/java/com/mySpring/springEx/survey/controller/SurveyController.java
src/main/java/com/mySpring/springEx/survey/controller/SurveyControllerImpl.java
src/main/java/com/mySpring/springEx/survey/dao/SurveyDAO.java
src/main/java/com/mySpring/springEx/survey/dao/SurveyDAOImpl.java
src/main/java/com/mySpring/springEx/survey/service/SurveyService.java
src/main/java/com/mySpring/springEx/survey/service/SurveyServiceImpl.java
src/main/java/com/mySpring/springEx/survey/vo/DetailVO.java
src/main/resources/mybatis/mappers/survey.xml
src/main/webapp/WEB-INF/views/location.jsp
src/main/webapp/WEB-INF/views/member/memberJoinForm.jsp
src/main/webapp/WEB-INF/views/survey/surveyForm.jsp
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

**- 각 동작마다 swalFire 적용 및 jQuery 처리해서 null값이 없게 하도록 수정했습니다**
등등 ..
- **SURVEY에 목록삭제 추가**

EditSurvey and EditJoin by SwalFire

---

src/main/java/com/mySpring/springEx/member/controller/MemberController.java
src/main/java/com/mySpring/springEx/member/controller/MemberControllerImpl.java
src/main/java/com/mySpring/springEx/member/dao/MemberDAO.java
src/main/java/com/mySpring/springEx/member/dao/MemberDAOImpl.java
src/main/java/com/mySpring/springEx/member/service/MemberService.java
src/main/java/com/mySpring/springEx/member/service/MemberServiceImpl.java
src/main/resources/mybatis/mappers/member.xml
src/main/resources/tiles/tiles_member.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member/myInfo.jsp
src/main/webapp/WEB-INF/views/university/universityConsortium.jsp
src/main/webapp/WEB-INF/views/university/universityIntro.jsp
src/main/webapp/resources/css/university/UniversityConsortium.css
target/classes/mybatis/mappers/member.xml
target/classes/tiles/tiles_member.xml

* 사용색상 변경
* dropdown hover 시
* 내정보 입력
* 내정보 수정
* 수정확인

MyInfo Page (내 정보페이지)

---

src/main/java/com/mySpring/springEx/common/pagination/mapper/PageMapper.java
src/main/java/com/mySpring/springEx/courseTake/controller/CourseTakeController.java
src/main/java/com/mySpring/springEx/courseTake/controller/CourseTakeControllerImpl.java
src/main/java/com/mySpring/springEx/courseTake/dao/CourseTakeDAO.java
src/main/java/com/mySpring/springEx/courseTake/dao/CourseTakeDAOImpl.java
src/main/java/com/mySpring/springEx/courseTake/service/CourseTakeService.java
src/main/java/com/mySpring/springEx/courseTake/service/CourseTakeServiceImpl.java
src/main/java/com/mySpring/springEx/courseTake/vo/CourseTakeVO.java
src/main/resources/mybatis/mappers/courseTake.xml
src/main/resources/mybatis/mappers/pagination.xml
src/main/webapp/WEB-INF/views/courseTake/courseApplyList.jsp
src/main/webapp/WEB-INF/views/courseTake/courseCompleteList.jsp

memberVO와 join 완료 (쿼리문은 pagination.xml에 있음)
courseVO와의 join 도 할 예정

join completed

---

src/main/java/com/mySpring/springEx/common/pagination/mapper/PageMapper.java
src/main/java/com/mySpring/springEx/partner/controller/PartnerContorollerImpl.java
src/main/java/com/mySpring/springEx/partner/controller/PartnerController.java
src/main/java/com/mySpring/springEx/partner/service/PartnerService.java
src/main/java/com/mySpring/springEx/partner/service/PartnerServiceImpl.java
src/main/resources/mybatis/mappers/pagination.xml
src/main/webapp/WEB-INF/views/partner/partnerList.jsp

partnerPAGING

---

src/main/java/com/mySpring/springEx/course/controller/CourseController.java
src/main/java/com/mySpring/springEx/course/controller/CourseControllerImpl.java
src/main/java/com/mySpring/springEx/course/dao/CourseDAO.java
src/main/java/com/mySpring/springEx/course/dao/CourseDAOImpl.java
src/main/java/com/mySpring/springEx/course/service/CourseService.java
src/main/java/com/mySpring/springEx/course/service/CourseServiceImpl.java
src/main/java/com/mySpring/springEx/course/vo/CourseVO.java
src/main/java/com/mySpring/springEx/syllabus/controller/SyllabusControllerImpl.java
src/main/java/com/mySpring/springEx/syllabus/dao/SyllabusDAOImpl.java
src/main/resources/mybatis/mappers/course.xml
src/main/resources/mybatis/mappers/syllabus.xml
src/main/resources/mybatis/model/modelConfig.xml
src/main/resources/tiles/tiles_course.xml
src/main/resources/tiles/tiles_syllabus.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/course/courseList.jsp
target/classes/mybatis/model/modelConfig.xml

강의계획서 검색, 체크박스를 통한 삭제기능 추가
courseVO 추가해서 과정 관리 페이지까지 띄움

courseVO추가해서 과정 관리 페이지 띄움

---

src/main/java/com/mySpring/springEx/member/controller/MemberControllerImpl.java
src/main/java/com/mySpring/springEx/member/dao/MemberDAO.java
src/main/java/com/mySpring/springEx/member/dao/MemberDAOImpl.java
src/main/java/com/mySpring/springEx/member/service/MemberService.java
src/main/java/com/mySpring/springEx/member/service/MemberServiceImpl.java
src/main/java/com/mySpring/springEx/partner/controller/PartnerContorollerImpl.java
src/main/java/com/mySpring/springEx/partner/controller/PartnerController.java
src/main/java/com/mySpring/springEx/partner/service/PartnerService.java
src/main/java/com/mySpring/springEx/partner/service/PartnerServiceImpl.java
src/main/resources/mybatis/mappers/courseTake.xml
src/main/resources/mybatis/mappers/member.xml
src/main/resources/mybatis/mappers/pagination.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/member/memberJoinForm.jsp
src/main/webapp/WEB-INF/views/partner/company/companyInfo.jsp
target/classes/mybatis/mappers/member.xml
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

* kt_user2를 사용하던 것에서 kt_user로 변경하였습니다.
*  현재 사용하는 kt_user2 들은 죄다 바꿨는데 문제가 있을 시 즉시 알려주세요.
* partner의 PK FK 사용 중입니다.

Edit database kt_user2 => kt_user

---

src/main/java/com/mySpring/springEx/member/controller/MemberControllerImpl.java
src/main/resources/mybatis/mappers/member.xml
target/classes/mybatis/mappers/member.xml

* 협력사 로그인이 안되던 오류를 수정했습니다.
* 이제 협력사 로그인의 경우, 협력사 정보를 login시 가져옵니다.

Edit Partner Login process

---

src/main/java/com/mySpring/springEx/courseTake/controller/CourseTakeController.java
src/main/java/com/mySpring/springEx/courseTake/controller/CourseTakeControllerImpl.java
src/main/java/com/mySpring/springEx/courseTake/dao/CourseTakeDAO.java
src/main/java/com/mySpring/springEx/courseTake/dao/CourseTakeDAOImpl.java
src/main/java/com/mySpring/springEx/courseTake/service/CourseTakeService.java
src/main/java/com/mySpring/springEx/courseTake/service/CourseTakeServiceImpl.java
src/main/java/com/mySpring/springEx/courseTake/vo/CourseTakeVO.java
src/main/resources/mybatis/mappers/courseTake.xml
src/main/resources/mybatis/mappers/pagination.xml
src/main/webapp/WEB-INF/views/courseTake/courseApplyList.jsp
src/main/webapp/resources/css/FormStyle.css
src/main/webapp/resources/css/style.css
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

승인대기 상태인 사람을 check 하고 신청승인버튼을 누르면 승인 으로 update

courseManagement(ADMIN) ApplyButton completed

---

.settings/org.eclipse.core.resources.prefs
src/main/java/com/mySpring/springEx/common/pagination/mapper/PageMapper.java
src/main/java/com/mySpring/springEx/courseTake/controller/CourseTakeController.java
src/main/java/com/mySpring/springEx/courseTake/controller/CourseTakeControllerImpl.java
src/main/java/com/mySpring/springEx/courseTake/dao/CourseTakeDAO.java
src/main/java/com/mySpring/springEx/courseTake/dao/CourseTakeDAOImpl.java
src/main/java/com/mySpring/springEx/courseTake/service/CourseTakeService.java
src/main/java/com/mySpring/springEx/courseTake/service/CourseTakeServiceImpl.java
src/main/java/com/mySpring/springEx/courseTake/vo/CourseTakeVO.java
src/main/java/com/mySpring/springEx/member/controller/MemberControllerImpl.java
src/main/java/com/mySpring/springEx/resume/controller/ResumeControllerImpl.java
src/main/resources/mybatis/mappers/courseTake.xml
src/main/resources/mybatis/mappers/pagination.xml
src/main/resources/tiles/tiles_member.xml
src/main/webapp/WEB-INF/views/courseTake/courseApplyList.jsp
src/main/webapp/WEB-INF/views/courseTake/courseCompleteList.jsp
src/main/webapp/WEB-INF/views/member/myCertificate.jsp
src/main/webapp/WEB-INF/views/member/myInfo.jsp
src/main/webapp/resources/css/style.css
target/classes/tiles/tiles_member.xml

1. 수강관리에 승인->승인버튼 추가
2. 삭제버튼 추가
3. 마이페이지 수강신청내역에 수료증출력부분 수정(수료상태가 아닐 시 빨간글씨로 미수료 출력)

buttons of courseApplyList for admin are added

---

.settings/org.eclipse.core.resources.prefs
src/main/java/com/mySpring/springEx/common/pagination/mapper/PageMapper.java
src/main/java/com/mySpring/springEx/courseTake/vo/CourseTakeVO.java
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

pageMapper 중복과 courseTakeVO 오류 수정

errors fixed

---

.settings/org.eclipse.core.resources.prefs
src/main/java/com/mySpring/springEx/common/pagination/mapper/PageMapper.java
src/main/java/com/mySpring/springEx/courseTake/vo/CourseTakeVO.java
src/main/resources/mybatis/mappers/course.xml
src/main/resources/tiles/tiles_course.xml
src/main/resources/tiles/tiles_courseTake.xml
src/main/resources/tiles/tiles_syllabus.xml
src/main/webapp/WEB-INF/views/common/side.jsp
src/main/webapp/WEB-INF/views/course/courseInformation.jsp
src/main/webapp/WEB-INF/views/course/courseList.jsp
src/main/webapp/WEB-INF/views/course/courseModify.jsp
src/main/webapp/WEB-INF/views/course/courseRegister.jsp
src/main/webapp/WEB-INF/views/course/courseSyllabusList.jsp
src/main/webapp/WEB-INF/views/course/userCourseList.jsp
src/main/webapp/WEB-INF/views/courseTake/courseApplyList.jsp
src/main/webapp/WEB-INF/views/syllabus/syllabusInformation.jsp
src/main/webapp/WEB-INF/views/syllabus/syllabusList.jsp
src/main/webapp/WEB-INF/views/syllabus/syllabusModify.jsp
src/main/webapp/WEB-INF/views/syllabus/syllabusRegister.jsp
src/main/webapp/resources/css/layoutAdmin.css
src/main/webapp/resources/css/style.css
src/main/webapp/resources/css/style2.css
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

ADMIN - 강의관리 width 정리 및 버튼 디자인 변경

button changed

---

src/main/resources/mybatis/mappers/partner.xml
src/main/webapp/WEB-INF/views/common/layoutAdmin.jsp
src/main/webapp/WEB-INF/views/common/side.jsp
src/main/webapp/WEB-INF/views/partner/company/companyApplyManage.jsp
src/main/webapp/WEB-INF/views/partner/company/companyEmployee.jsp
src/main/webapp/WEB-INF/views/partner/company/companyInfo.jsp
src/main/webapp/WEB-INF/views/syllabus/syllabusList.jsp
src/main/webapp/WEB-INF/views/syllabus/syllabusRegister.jsp
src/main/webapp/resources/css/common/sideBar.css
src/main/webapp/resources/css/layoutAdmin.css

.container부분에
```
.container {
display: flex;
flex-wrap: wrap;
width: 75%;
justify-content: space-around;
flex-direction: column;
}
```
를 넣어서 작성하시면 되겠습니다.

SideBar edit

---

src/main/java/com/mySpring/springEx/member/controller/MemberController.java
src/main/java/com/mySpring/springEx/member/controller/MemberControllerImpl.java
src/main/java/com/mySpring/springEx/member/dao/MemberDAO.java
src/main/java/com/mySpring/springEx/member/dao/MemberDAOImpl.java
src/main/java/com/mySpring/springEx/member/service/MemberService.java
src/main/java/com/mySpring/springEx/member/service/MemberServiceImpl.java
src/main/java/com/mySpring/springEx/suggestion/vo/SuggestionVO.java
src/main/resources/mybatis/mappers/member.xml
src/main/resources/tiles/tiles_partner.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/common/side.jsp
src/main/webapp/WEB-INF/views/location.jsp
src/main/webapp/WEB-INF/views/member/apply.jsp
src/main/webapp/WEB-INF/views/partner/jobOpeningList.jsp
src/main/webapp/WEB-INF/views/partner/jobOpeningPost.jsp
target/classes/mybatis/mappers/member.xml

Partner suggestion user

---

.settings/org.eclipse.core.resources.prefs
src/main/webapp/WEB-INF/views/course/userCourseInformation.jsp
src/main/webapp/WEB-INF/views/partner/company/companyApplyManage.jsp
src/main/webapp/WEB-INF/views/partner/company/companyEmployee.jsp
src/main/webapp/WEB-INF/views/partner/company/companyInfo.jsp
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

utf-8 modified

---

.settings/org.eclipse.core.resources.prefs
src/main/java/com/mySpring/springEx/common/interceptor/Auth.java
src/main/java/com/mySpring/springEx/common/interceptor/AuthViewInterceptor.java
src/main/java/com/mySpring/springEx/common/interceptor/ViewNameInterceptor.java
src/main/java/com/mySpring/springEx/member/controller/MemberControllerImpl.java
src/main/java/com/mySpring/springEx/member/vo/MemberVO.java
src/main/java/com/mySpring/springEx/partner/controller/PartnerControllerImpl.java
src/main/java/com/mySpring/springEx/question/controller/QuestionControllerImpl.java
src/main/java/com/mySpring/springEx/resume/vo/ResumeVO.java
src/main/resources/mybatis/mappers/partner.xml
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
src/main/webapp/WEB-INF/views/error/400.jsp
src/main/webapp/WEB-INF/views/error/401.jsp
src/main/webapp/WEB-INF/views/error/404.jsp
src/main/webapp/WEB-INF/views/error/408.jsp
src/main/webapp/WEB-INF/views/error/502.jsp
src/main/webapp/WEB-INF/views/error/503.jsp
src/main/webapp/WEB-INF/views/error/504.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/partner/company/companyApplyManage.jsp

Partner check page

---

src/main/webapp/WEB-INF/views/partner/company/companyApplyManage.jsp

companyApplyPage UTF-8 Error

---

src/main/webapp/WEB-INF/views/common/footer.jsp

Footer Top Change

---

src/main/webapp/WEB-INF/views/common/header.jsp

Add Normal User header

---

src/main/java/com/mySpring/springEx/member/service/MemberServiceImpl.java
src/main/resources/mybatis/mappers/member.xml
src/main/webapp/WEB-INF/views/member/memberJoinForm.jsp
src/main/webapp/WEB-INF/views/member/memberPartnerList.jsp

회원가입 ktu 안뜨게, Info Edit 500 수정

Munsu survey

---

src/main/java/com/mySpring/springEx/question/controller/QuestionControllerImpl.java
src/main/webapp/WEB-INF/views/question/listQuestion.jsp

ADIM questionList add ordering detail

Questionlast

---

src/main/webapp/WEB-INF/views/partner/company/companyApplyManage.jsp
src/main/webapp/WEB-INF/views/partner/partnerList.jsp
src/main/webapp/WEB-INF/views/resume/resume.jsp
src/main/webapp/WEB-INF/views/resume/resumeAdmin.jsp
src/main/webapp/WEB-INF/views/resume/resumeWriteProject.jsp

Last resume

---

src/main/webapp/WEB-INF/views/partner/partnerList.jsp
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

lastPartnerCSS

---

src/main/java/com/mySpring/springEx/common/interceptor/AuthViewInterceptor.java
src/main/java/com/mySpring/springEx/resume/controller/ResumeControllerImpl.java
src/main/webapp/WEB-INF/views/partner/company/companyApplyManage.jsp
src/main/webapp/WEB-INF/views/resume/resume.jsp
src/main/webapp/WEB-INF/views/resume/resumeAdmin.jsp
src/main/webapp/WEB-INF/views/resume/resumeWrite.jsp
src/main/webapp/WEB-INF/views/resume/resumeWriteCareer.jsp
src/main/webapp/WEB-INF/views/resume/resumeWriteDetail.jsp
src/main/webapp/WEB-INF/views/resume/resumeWriteProject.jsp
src/main/webapp/WEB-INF/views/resume/resumeWriteSelf.jsp

Resume edit picture

---

src/main/java/com/mySpring/springEx/common/interceptor/AuthViewInterceptor.java
src/main/java/com/mySpring/springEx/common/util/FileUtils.java
src/main/java/com/mySpring/springEx/notice/controller/NoticeControllerImpl.java
src/main/resources/mybatis/mappers/notice.xml
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF

Check notice

---

src/main/resources/mybatis/mappers/partner.xml
src/main/webapp/WEB-INF/views/member/apply.jsp
src/main/webapp/WEB-INF/views/partner/jobOpeningList.jsp
src/main/webapp/WEB-INF/views/partner/jobOpeningPost.jsp

Job opening list css
